using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FiveCast
{
    internal static class CityList
    {
        public static List<string> Names => new List<string>
        {
            "Sofia",
            "Varna",
            "Plovdiv",
            "Burgas",
            "Ruse",
            "Stara Zagora",
            "Pleven",
            "Sliven",
            "Pernik",
            "Pazardzhik",
            "Dobrich",
            "Shumen",
            "Haskovo",
            "Veliko Tarnovo",
            "Blagoevgrad",
            "Yambol",
            "Kazanlak",
            "Asenovgrad",
            "Kyustendil",
            "Vratsa",
            "Gabrovo",
            "Targovishte",
            "Kardzhali",
            "Vidin",
            "Razgrad",
            "Svishtov",
            "Silistra",
            "Dupnitsa",
            "Montana",
            "Lovech",
            "Dimitrovgrad",
            "Smolyan",
            "Gorna Oryahovitsa",
            "Petrich",
            "Gotse Delchev",
            "Aytos",
            "Rakovski",
            "Omurtag",
            "Velingrad",
            "Isperih",
            "Lom",
            "Karlovo",
            "Panagyurishte",
            "Botevgrad",
            "Peshtera",
            "Veliki Preslav",
            "Pomorie",
            "Nesebar",
            "Lyaskovets",
            "Novi Pazar",
            "Provadia",
            "Razlog",
            "Zlatograd",
            "Kozloduy",
            "Kostinbrod",
            "Bankya",
            "Stamboliyski",
            "Etropole",
            "Momchilgrad",
            "Devnya",
            "Rakitovo",
            "Sopot",
            "Septemvri",
            "Krichim",
            "Byala",
            "Aksakovo",
            "Beloslav",
            "Elin Pelin",
            "Slivnitsa",
            "Madan",
            "Aydemir",
            "Devin",
            "Lozen",
            "Varshets",
            "Saedinenie",
            "Bistritsa",
            "Bozhurishte",
            "Suvorovo",
            "Perushtitsa",
            "Dolna Banya",
            "Vetovo",
            "Kazichene",
            "Ignatievo",
            "Kostandovo",
            "Bukovlak",
            "Koynare",
            "Slavyanovo",
            "Trud",
            "Kalipetrovo",
            "Sapareva Banya",
            "Malo Konare",
            "Varbitsa",
            "Marten",
            "Debelets",
            "Vladaya",
            "Parvenets",
            "Sarnitsa",
            "Sveti Vlas",
            "Rudozem",
            "Topolchane",
            "Brestovitsa",
            "Aleko Konstantinovo",
            "Gulyantsi",
            "Nikolaevo",
            "Rogosh",
            "Banya",
            "Kran",
            "Topoli",
            "Pancharevo",
            "Kamenar",
            "Ivaylo",
            "Gurkovo",
            "Sotirya",
            "Ruen",
            "Kableshkovo",
            "Vetren",
            "Dolna Oryahovitsa",
            "Voluyak",
            "German",
            "Buhovo",
            "Kalofer",
            "Kalekovets",
            "Nikolovo",
            "Ravda",
            "Glozhene",
            "Novo Selo",
            "Kurtovo Konare",
            "Skutare",
            "Ablanitsa",
            "Sadovo",
            "Chepintsi",
            "Parvomaytsi",
            "Draganovo",
            "Ognyanovo",
            "Valkosel",
            "Rakovski",
            "Kilifarevo",
            "Glavinitsa",
            "Svetovrachane",
            "Bregovo",
            "Aheloy",
            "Krushare",
            "Gradina",
            "Startsevo",
            "Obzor",
            "Batanovtsi",
            "Tsaratsovo",
            "Voyvodinovo",
            "Borovo",
            "Balgarovo",
            "Petarch",
            "Chernogorovo",
            "Kokalyane",
            "Oreshak",
            "Dragichevo",
            "Ostrovo",
            "Mokrishte",
            "Yahinovo",
            "Kostievo",
            "Kraynitsi",
            "Aleksandrovo",
            "Sinitovo",
            "Ezerovo",
            "Resen",
            "Graf Ignatievo",
            "Seliminovo",
            "Uzundzhovo",
            "Busmantsi",
            "Lyuben Karavelovo",
            "Lesnovo",
            "Byal Izvor",
            "Merichleri",
            "Polikrayshte",
            "Divotino",
            "Ravnets",
            "Kermen",
            "Kukorevo",
            "Samoranovo",
            "Stozher",
            "Zheleznitsa",
            "Slokoshtitsa",
            "Negovan",
            "Orizare",
            "Trivoditsi",
            "Krepost",
            "Bistritsa",
            "Grivitsa",
            "Mirovyane",
            "Saraya",
            "Stratsin",
            "Planinitsa",
            "Krivina",
            "Karageorgievo",
            "Prosenik",
            "Vinogradets",
            "Tankovo",
            "Maglen",
            "Tsarev Brod",
            "Tranak",
            "Razhitsa",
            "Shipka",
            "Basarbovo",
            "Karabunar",
            "Dzherman",
            "Kosharitsa",
            "Konstantinovo",
            "Benkovski",
            "Yabalchevo",
            "Galabets",
            "Chervena Voda",
            "Veselinovo",
            "Bata",
            "Golyamo Novo",
            "Dolni Bogrov",
            "Aldomirovtsi",
            "Karapelit",
            "Novo Selo",
            "Belogradets",
            "Sandrovo",
            "Gabrovnitsa",
            "Yabalkovo",
            "Vaglen",
            "Vardun",
            "Gorni Bogrov",
            "Marchaevo",
            "Zaychar",
            "Banitsa",
            "Voyvodovo",
            "Malevo",
            "Opalchensko",
            "Semerdzhievo",
            "Zvezditsa",
            "Marinka",
            "Gyulyovtsa",
            "Gluhar",
            "Boboshevo",
            "Hadzhievo",
            "Vaklinovo",
            "Pisarevo",
            "Varbitsa",
            "Kladnitsa",
            "Dolen",
            "Patalenitsa",
            "Gorski Izvor",
            "Stefanovo",
            "Borovo",
            "Dobromir",
            "Snyagovo",
            "Voysil",
            "Cherven Breg",
            "Vresovo",
            "Kadievo",
            "Vinitsa",
            "Izvorsko",
            "Mortagonovo",
            "Dobroslavtsi"
        };
    }
}
